#!/usr/bin/env bash
set -ex

# Setup alias and environment variables
mkdir -p /home/centos8 # Will become HOME and WORKDIR
touch /home/centos8/.bashrc
{
    echo 'alias ls="ls --color=auto"'
    echo 'alias ll="ls -hla"'
    echo 'export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]centos8:\[\033[33;1m\]\w\[\033[m\]$ "' # Prettify prompt
    echo 'export PATH=$PATH:/miniconda3/bin'
} >> /home/centos8/.bashrc

# Install and setup conda
curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
sh Miniconda3-latest-Linux-x86_64.sh -b -p /miniconda3
rm -rf Miniconda3-latest-Linux-x86_64.sh
export PATH=$PATH:/miniconda3/bin

# Update conda
conda update -n base -c defaults conda
conda config --set auto_activate_base false

# Install WhatsHap
# conda install -y -c conda-forge mamba
# mamba create -y -c conda-forge -c bioconda -n whatshap whatshap nomkl

# Add to PATH with conda activation
# touch /usr/local/bin/run_whatshap
# chmod 755 /usr/local/bin/run_whatshap
# echo -e '#!/bin/bash\nsource /home/whatshap/.bashrc\neval "$(conda shell.bash hook)"\nconda activate whatshap\n\nwhatshap $@\n' > /usr/local/bin/run_whatshap
